name: "Hello Actions"
description: "Say hi"
author: "octocat@hithub.com"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "world"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
